### ISSUE TITLE
isAbout contains string "No concept needed"

### ISSUE THREAD

**Issue by dbkeator** [sanuann/nidmterms-ui#29]
When the user selects to not attach a concept to a variable, the isAbout property in the JSON file exported contains this entry:

```
"isAbout": [
            "No concept needed"
        ],
```

In these cases the isAbout property just shouldn't be included.

**Comment by sanuann** [comment]
resolved with commit `1b6dfa5f8163a8a08f2cc0048570516993875a8c`
